name: Proceso Completo de Ingesta y Limpieza de Datos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  data_processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Configurar credenciales de Kaggle
        run: |
          mkdir -p ~/.kaggle
          printf '{"username": "%s", "key": "%s"}' "${{ secrets.KAGGLE_USERNAME }}" "${{ secrets.KAGGLE_KEY }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Sincronizar con el repositorio remoto
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fdx

      - name: Ejecutar scripts de procesamiento
        run: |
          python src/ingestion.py
          python src/cleaning.py

      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-procesamiento
          path: |
            src/static/auditoria/*.txt
            src/static/csv/*.csv
            src/static/db/*.db

      - name: Commit y Push de los cambios
        run: |
          git add src/static/auditoria/*.txt || true
          git add src/static/csv/*.csv || true
          git commit -m "Actualización automática de evidencias de procesamiento" || echo "No hay cambios para commitear"
          git pull origin main --rebase || true
          git push origin main || echo "No se pudo hacer push debido a conflictos"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}